// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoe_WebShop.Data;

#nullable disable

namespace Shoe_WebShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240310172012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shoe_WebShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Designed for runners, providing support and cushioning for optimal performance.",
                            Name = "Running Shoes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Stylish and comfortable shoes for women.",
                            Name = "Women's Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Stylish and comfortable shoes for men.",
                            Name = "Men's Shoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
